config_description: These are default Ansible variables consumed by various templates in Websauna deployment. They are generated based on core information you give it. You can override any of these variables by including another variable file after default.yml in your playbook using``include_vars`` Ansible command after ``default.yml`` is included in your playbook.

# List of native dependencies needed to install and run Websauna
dependencies:
    - git
    - supervisor
    - build-essential
    - libfreetype6-dev
    - libncurses5-dev
    - libxml2-dev
    - libxslt1-dev
    - libjpeg-dev
    - libpng12-dev
    - fail2ban
    - gettext
    - duplicity
    - python-boto
    - python-virtualenv
    - libpq-dev
    - libffi-dev
    - libzmq3-dev
    - ntp
    - postgresql-client-common
    - postgresql-client-9.3

# What is the name of the unix user owning /srv/pyramid/myapp files
# DO NOT CHANGE - the current version of Ansible does not allow variables in become_user
wsgi_user: wsgi

# What is the name of the unix group owning /srv/pyramid/myapp files
wsgi_group: wsgi

#: Where does the git checkout goes on the server
deploy_location: "/srv/pyramid/{{ package_name }}"

# Deploy production.ini and production-secrets.ini here
websauna_conf_folder: "{{ deploy_location }}/{{ package_path }}/conf"

# The server path where we generate INI file for Pyramid. Ansible will fill in details like database.
websauna_config_file: "{{ websauna_conf_folder }}/generated.ini"

# Where we place secrets INI file on our server
websauna_secrets_ini_file: "{{ websauna_conf_folder }}/generated-secrets.ini"

# Where to deploy WSGI entry script
websauna_wsgi_file: "{{ websauna_conf_folder }}/websauna.wsgi"

# The [includes] section for generated configuration file
websauna_config_includes: >
    resource://{{ package_name }}/conf/{{ site_mode }}.ini
    resource://websauna/conf/production.ini
    resource://{{ package_name }}/conf/base.ini
    resource://websauna/conf/base.ini

# Generated PostgreSQL database n ame.
db_name: "{{ site_id }}_{{ site_mode }}"

# Generated PostgreSQL user. Must match UNIX user running the application.
db_user: "{{ wsgi_user }}"

# Generated PostgreSQL user password. Not used as the default PSQL authentication mode is trust.
db_password: "{{ wsgi_user }}"

# SQLAlchemy connection URL - by default PostgreSQL does not require
# authentication for local users
db_sqlalchemy_url: "postgresql://localhost/{{ db_name }}"

# Do a SQL dump before running migration scripts against the database. Expensive on larger systems.
db_backup_dump_before_migration: true

# Python versions to install on the server.
python_versions: [3.5]

# Name of the Python interpreter for creating the Websauna application :term:`virtual environment`.
python_interpreter: python3.5

# PyPi mirror from where the packages are downloaded from. For an enterprise setup you might want to point this to your own server. For example custom PyPi hosting, see http://doc.devpi.net/
pypi_index_url: https://pypi.python.org/simple

# -----------------------
# Celery
# -----------------------

# Allow to debug Celery woes by enforcing log level on command line
celery_log_level: info

# ------------------------------------------------
# Complex settings below
# ------------------------------------------------

# ----------------------------------------------------
# Postfix
# ----------------------------------------------------

# Which is the domain name where our outboound email comes from
postfix_domain: "{{ server_email_domain }}"

# Sysadmin email for Postfix notify emails
postfix_notify_email: "{{ notify_email }}"

# ----------------------------------------------------
# uWSGI
# ----------------------------------------------------

# uWSGI version to install
uwsgi_version: 2.0.14

# Template used for uWSGI config
uwsgi_config_source: uwsgi.ini

# Where uWSGI config is placed on the server
uwsgi_config_target: "{{ websauna_conf_folder }}/uwsgi.ini"

# ----------------------------------------------------
# nginx
# ----------------------------------------------------

# A certificate file path on local environment to copy over to the server. Usually like ``certificate.pem``. Note that certificate and certificate key can be in same .pem file. Leave empty if using Let's Encrypt.
local_certificate_file:

# A certificate file key on local environment to copy over to the server. Usually like ``certificate.pem``. Note that certificate and certificate key can be in same .pem file. Leave empty if using Let's Encrypt.
local_key_file:

# Source template name for Nginx configuration
nginx_config: nginx.conf

# Where does Nginx access log file goes
nginx_access_log: /var/log/nginx/{{ site_id }}.access.log

# Where does Nginx error log file goes
nginx_error_log: /var/log/nginx/{{ site_id }}.error.log


# ----------------------------------------------------
# PostgreSQL
# ----------------------------------------------------

# Installed PostgreSQL version
postgresql_version: 9.5

postgresql_ext_install_dev_headers: yes
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'

postgresql_admin_user: "postgres"
postgresql_default_auth_method: "trust"

postgresql_cluster_name: "main"
postgresql_cluster_reset: false

postgresql_ext_postgis_version: 2.2
postgresql_ext_install_postgis: yes

# List of databases to be created
# By default include PostgreSQL PostGIS support (Geotypes), UUID and HSTORE
postgresql_databases:
  - name: "{{ db_name }}"
    hstore: yes
    uuid_ossp: yes
    gis: yes

# List of users to be created (optional)
postgresql_users:
  - name: "{{ db_user }}"
    pass: "{{ db_password }}"
    encrypted: no       # denotes if the password is already encrypted.

# List of user privileges to be applied (optional)
postgresql_user_privileges:
  - name: "{{ db_user }}"                   # user name
    db: "{{ db_name }}"                  # database
    priv: "ALL"                 # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
    role_attr_flags: "CREATEDB" # role attribute flags


# ----------------------------------------------------
# IPython Notebook
# ----------------------------------------------------

# Where created .ipynb files and IPython Notebook startup and error logs are stored
pyramid_notebook_notebook_folder: "{{ deploy_location}}/notebooks"

# ----------------------------------------------------
# Supervisor
# ----------------------------------------------------

# Supervisor config template. Create templates folder and supply your own supervisor startup handlers by giving a custom config filename here.
supervisor_config: supervisor.conf